--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flashcard_sets; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.flashcard_sets (
    id bigint NOT NULL,
    name text NOT NULL,
    user_id uuid NOT NULL,
    visibility text DEFAULT 'private'::text NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    deleted_at timestamp with time zone,
    is_default boolean DEFAULT false NOT NULL
);


ALTER TABLE public.flashcard_sets OWNER TO supabase_admin;

--
-- Name: flashcard_sets_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.flashcard_sets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flashcard_sets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flashcards; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.flashcards (
    id bigint NOT NULL,
    word text NOT NULL,
    definition text NOT NULL,
    set_id bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.flashcards OWNER TO supabase_admin;

--
-- Name: flashcards_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.flashcards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flashcards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flashcard_sets flashcard_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.flashcard_sets
    ADD CONSTRAINT flashcard_sets_pkey PRIMARY KEY (id);


--
-- Name: flashcards flashcards_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.flashcards
    ADD CONSTRAINT flashcards_pkey PRIMARY KEY (id);


--
-- Name: flashcard_sets flashcard_sets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.flashcard_sets
    ADD CONSTRAINT flashcard_sets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: flashcards set_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.flashcards
    ADD CONSTRAINT set_id_fkey FOREIGN KEY (set_id) REFERENCES public.flashcard_sets(id) ON DELETE CASCADE;


--
-- Name: flashcard_sets Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY "Enable delete for users based on user_id" ON public.flashcard_sets USING ((auth.uid() = user_id));


--
-- Name: flashcard_sets; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.flashcard_sets ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE flashcard_sets; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.flashcard_sets TO postgres;
GRANT ALL ON TABLE public.flashcard_sets TO anon;
GRANT ALL ON TABLE public.flashcard_sets TO authenticated;
GRANT ALL ON TABLE public.flashcard_sets TO service_role;


--
-- Name: SEQUENCE flashcard_sets_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.flashcard_sets_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.flashcard_sets_id_seq TO anon;
GRANT ALL ON SEQUENCE public.flashcard_sets_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.flashcard_sets_id_seq TO service_role;


--
-- Name: TABLE flashcards; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.flashcards TO postgres;
GRANT ALL ON TABLE public.flashcards TO anon;
GRANT ALL ON TABLE public.flashcards TO authenticated;
GRANT ALL ON TABLE public.flashcards TO service_role;


--
-- Name: SEQUENCE flashcards_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.flashcards_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.flashcards_id_seq TO anon;
GRANT ALL ON SEQUENCE public.flashcards_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.flashcards_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--
