name: CodeClimate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd web && yarn install --frozen-lockfile
      - name: Push to Codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          workingDirectory: ${{github.workspace}}/web
          coverageCommand: yarn test:coverage
          coverageLocations: |
            ${{github.workspace}}/web/coverage/lcov.info:lcov
