name: Flyctl
on:
  push:
    branches:
      - "main"
    paths:
      - "api/**"

jobs:
  deploy:
    name: Fly me to the moon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd api/ && flyctl deploy --remote-only -r ams -r sin -r lax
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
