name: WIP
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  WIP:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/wip@v1
        with:
          setFailed: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
